Added hexdump to token-key processing, so it won't have null-bytes

diff --git a/bin/systemd_password_cache_cleanup b/bin/systemd_password_cache_cleanup
--- a/bin/systemd_password_cache_cleanup
+++ b/bin/systemd_password_cache_cleanup
@@ -7,25 +7,27 @@ pw_seed=/run/initramfs/.password.seed
 rsa_info=$(grep -o 'rd.rsa=[^[:space:]]\+' /proc/cmdline)
 rsa_info=${rsa_info#*=}
 
-update_seed() {
-	rsa_src=${rsa_info%/*}
-	rsa_dev=${src%-*}
-	rsa_offset=${src#*-}
-	rsa_key=${rsa_info#*/}
-
+process_seed() {
 	# Create old/new seed/keys
-	pkcs15-crypt -r0 -k "$rsa_key" --sign -i "$pw_seed" -R >"${pw_cache}.old" \
-		&& dd if=/dev/urandom of="$pw_seed" bs=256 count=1 status=noxfer 2>/dev/null \
-		&& pkcs15-crypt -r0 -k "$rsa_key" --sign -i "$pw_seed" -R >"${pw_cache}.new" \
-		|| return 1
+	pkcs15-crypt -r0 -k "$rsa_key" --sign -i "$pw_seed" -R |
+			hexdump -e '"%x"' >"${pw_cache}.old"
+	[[ $? -ne 0 || ${PIPESTATUS[0]} -ne 0 || ! -s "${pw_cache}.old" ]] && return 1
+	dd if=/dev/urandom of="$pw_seed" bs=256 count=1 status=noxfer 2>/dev/null \
+		&& pkcs15-crypt -r0 -k "$rsa_key" --sign -i "$pw_seed" -R |
+			hexdump -e '"%x"' >"${pw_cache}.new"
+	[[ $? -ne 0 || ${PIPESTATUS[0]} -ne 0 || ! -s "${pw_cache}.new" ]] && return 1
+	return 0
+}
 
+update_seed() {
 	# Devices to process
 	devs=( $(awk 'match($1, /luks-(.*)/, a) {system("blkid -U " a[1])}' /etc/crypttab) )
+	[[ ${#devs[@]} -eq 0 ]] && return 0
 
 	# Add new key, counting failures
 	failures=0
-	for $dev in ${devs[@]}; do
-		cryptsetup -d "${pw_cache}.old" luksAddKey "$dev" "${pw_cache}.new"
+	for dev in ${devs[@]}; do
+		cryptsetup -q -i100 -d "${pw_cache}.old" luksAddKey "$dev" "${pw_cache}.new"
 		[[ "$?" -ne 0 ]] && (( failures += 1 ))
 	done
 	[[ $failures -gt 0 ]] && echo >&2 "*** Failed to add new key to $failures devices ***"
@@ -33,8 +35,8 @@ update_seed() {
 
 	# Remove old keys
 	failures=0
-	for $dev in ${devs[@]}; do
-		cryptsetup -d "${pw_cache}.new" luksRemoveKey "$dev" "${pw_cache}.old"
+	for dev in ${devs[@]}; do
+		cryptsetup -q luksRemoveKey "$dev" "${pw_cache}.old"
 		[[ "$?" -ne 0 ]] && (( failures += 1 ))
 	done
 	[[ $failures -gt 0 ]] && echo >&2 "*** Failed to remove old key from $failures devices ***"
@@ -44,10 +46,24 @@ update_seed() {
 	dd if="$pw_seed" of=/dev/"$rsa_dev"\
 			bs=256 seek="$rsa_offset" count=1 status=noxfer 2>/dev/null \
 		|| return 1
+
+	return 0
 }
 
 if [[ -f "$pw_seed" && -n "$rsa_info" ]]
-then update_seed || echo >&2 "Failed to update rsa seed"
+then
+	rsa_src=${rsa_info%/*}
+	rsa_dev=${rsa_src%-*}
+	rsa_offset=${rsa_src#*-}
+	rsa_key=${rsa_info#*/}
+
+	# Foreground because it locks token
+	process_seed || echo >&2 "Failed to process rsa seed"
+	# Backgroud - slow
+	( update_seed || echo >&2 "Failed to update rsa seed"
+		rm -f "$pw_seed" "$pw_cache"{,.old,.new} ) &
+	disown
+else rm -f "$pw_seed" "$pw_cache"{,.old,.new}
 fi
 
-rm -f "$pw_seed" "$pw_cache"{,.old,.new}
+exit 0
